### ISSUE TITLE
move function to __init__ ?

### ISSUE THREAD

**Issue by pwalter2** [CoolNamesAllTaken/svb#16]
https://github.com/CoolNamesAllTaken/svb/blob/555cf89bbbda047a3b0d3e57220bd4c72e8f02a5/code/svb-docker/python/svb_web/core/models.py#L24

I feel like this function belongs in the "_ _ init _ _" method of the model class.
It is currently in the core.models namespace, which feels wrong.
Would we expect other code to use this function?

**Comment by CoolNamesAllTaken** [comment]
This is a good point, I'll add a `create` method similar to what's suggested in [this thread](https://stackoverflow.com/questions/843580/writing-a-init-function-to-be-used-in-django-model).

**Comment by CoolNamesAllTaken** [comment]
I actually did it a little differently, by overriding the model save function per @cahogan 's recommendation.

Should be fixed by https://github.com/CoolNamesAllTaken/svb/pull/21
