### ISSUE TITLE
"title" field in wrong class?

### ISSUE THREAD

**Issue by pwalter2** [CoolNamesAllTaken/svb#17]
https://github.com/CoolNamesAllTaken/svb/blob/555cf89bbbda047a3b0d3e57220bd4c72e8f02a5/code/svb-docker/python/svb_web/core/models.py#L59

I assume that "title" is meant to be part of the NewsArticle class?

**Comment by CoolNamesAllTaken** [comment]
NewsArticle stuff is written by @Morgan10E ! She might have a better idea about what's up.
