### ISSUE TITLE
inherit from forms.ModelForm rather than redefining customer_id field?

### ISSUE THREAD

**Issue by pwalter2** [CoolNamesAllTaken/svb#19]
https://github.com/CoolNamesAllTaken/svb/blob/555cf89bbbda047a3b0d3e57220bd4c72e8f02a5/code/svb-docker/python/svb_web/core/forms.py#L4

customer_id is defined twice (once in the form, once in the model)

Maybe the following would work?
```
class CustomerLookupForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ["customer_id"]

```

**Comment by CoolNamesAllTaken** [comment]
Resolved.
