### ISSUE TITLE
implement get_absolute_url() for this Model

### ISSUE THREAD

**Issue by pwalter2** [CoolNamesAllTaken/svb#22]
https://github.com/CoolNamesAllTaken/svb/blob/6de249c6e61c556afe266b948cac0bbe21074fb1/code/svb-docker/python/svb_web/core/models.py#L49

Since each Account model will probably need its own URL, we should implement the get_absolute_url method.
See:
https://docs.djangoproject.com/en/4.2/ref/models/instances/#get-absolute-url

This method will be particularly useful because an instance of Account can be passed to a ReceiptPrinter instance method, and the instance method will enable printing out a QR code of the account URL.

**Comment by CoolNamesAllTaken** [comment]
Good idea, this probably falls into @cahogan 's bucket since she is working on the public account interface.

**Comment by CoolNamesAllTaken** [comment]
Done!
